### ISSUE TITLE
[Feat] Swagger 세팅

### ISSUE THREAD

**Issue by geniusYoo** [jaksim-us/Jaksim-Server#10]
## ☑️ 어떤 기능인가요?
프로젝트 Swagger 세팅

## ☑️ TODO
- [x] Swagger 의존성 추가
- [x] build.gradle 주석 추가 & 정리
- [x] HealthCheckController에 Swagger 적용
- [x] 로그인 API Swagger Interface
